[CONEXAO]
BANCO=SQLite
DATABASE=C:\Bancos\SQLite\RMSYSDB.db

#######################################
#BANCO=MySQL
#SERVIDOR=localhost
#PORTA=3306
#DATABASE=RMSYSDB
#USERNAME=RMSYSDB
#PASSWORD=123456
#######################################